import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SocketContextProvider } from "./context/Socket";
import { RoomContextProvider } from "./context/RoomContext";
import { UserContextProvider } from "./context/UserContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SocketContextProvider>
          <UserContextProvider>
            <RoomContextProvider>
              {children}
            </RoomContextProvider>
          </UserContextProvider>
        </SocketContextProvider>
      </body>
    </html>
  );
}
